language: node_js
node_js:
- "10.15.3"
deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: "ACCESS_KEY_ID"
  secret_access_key:
    secure: "SECRET_ACCESS_KEY"
  region: us-west-2
  app: gus-graphql-apollo-server
  env: gus-graphql-apollo-server-dev
  bucket_name: elasticbeanstalk-us-west-2-248302884041
  bucket_path: gus-graphql-apollo-server