language: node_js
node_js:
- "10.15.3"
deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: "Encrypted <access-key-id>="
  secret_access_key:
    secure: "Encrypted <secret-access-key>="
  region: us-west-2
  app: gus-graphql-apollo-server
  env: gus-graphql-apollo-server-dev
  bucket_name: elasticbeanstalk-us-west-2-248302284041